### ISSUE TITLE
Not instantiable – yii\di\NotInstantiableException

### ISSUE THREAD

**Issue by kevadamson** [bhashkar007/guest-entries-notification#10]
I get this error when clicking settings after installing:
```
Not instantiable – yii\di\NotInstantiableException
Failed to instantiate component or class "by\guestentriesnotification\assetbundles\guestentriesnotification\GuestEntriesNotificationAsset".
Caused by: ReflectionException
Class by\guestentriesnotification\assetbundles\guestentriesnotification\GuestEntriesNotificationAsset does not exist
in /home/.../.../.../vendor/yiisoft/yii2/di/Container.php at line 508
```

**Comment by fdelaneau** [comment]
Same problem here 😓
Craft 3.7.13 running on PHP 7.4.23 and MySQL 5.6.41

**Comment by bhashkar007** [comment]
@fdelaneau @kevadamson Fixed the issue. Please try installing again. Thanks

**Comment by fdelaneau** [comment]
@bhashkar007 Thanks for the quick answer 👍

I updated to 1.0.1 but it didn't fix the problem for me 😓
I still get the exact same error at the line 508.

**Comment by fdelaneau** [comment]
Sorry, I didn't noticed the version number didn't change, so Composer could do the update. I’ll try a manual upgrade.

**Comment by fdelaneau** [comment]
And it works ! 🥳

**Comment by bhashkar007** [comment]
Glad to know 👍

**Comment by kevadamson** [comment]
> Sorry, I didn't noticed the version number didn't change, so Composer could do the update. I’ll try a manual upgrade.

How did you manually upgrade? I seem to be stuck on 1.0.1 ...

**Comment by fdelaneau** [comment]
> How did you manually upgrade? I seem to be stuck on 1.0.1 ...

I donwloaded the zip file from GitHub then replaced the content of the folder `guest-entries-notification` in `vendor/by` on my server 😊

**Comment by fdelaneau** [comment]
It is to my knowledge the only way to upgrade until the author updates the composer file to change the plugin version number.

**Comment by kevadamson** [comment]
@bhashkar007 Just a heads up:

![image](https://user-images.githubusercontent.com/1021744/134327762-4cc54016-082a-4408-81d7-13e99ddb4d89.png)

https://packagist.org/packages/by/guest-entries-notification

**Comment by kevadamson** [comment]
Hi. Can this get updated on packagist? I'd prefer not to be manually editing the vendor folder ...

**Comment by kevadamson** [comment]
@fdelaneau Not sure you are still using this plugin, but this is how to get the latest version using composer:

```
"require": {
    "by/guest-entries-notification": "1.0.2"
},
"repositories": [
    {
        "type": "package",
        "package": {
            "name": "by/guest-entries-notification",
            "version": "1.0.2",
            "source": {
                "url": "https://github.com/bhashkar007/guest-entries-notification.git",
                "type": "git",
                "reference": "v1.0.2"
            }
        }
    }
],
```

**Comment by Stalex89** [comment]
The Craft Plugin Store still contains version 1.0.1 without a fix, is it possible to put the latest version there ? Thank you 

![Screenshot 2022-03-02 at 11 22 08](https://user-images.githubusercontent.com/23526237/156343255-db7ffd91-da38-4645-a153-e29a07f94b96.png)

**Comment by mark-chief** [comment]
@bhashkar007 please can you allow this latest fixed version to be downloaded in the craft plugin store for craft 3? it's still 1.0.1

**Comment by mark-chief** [comment]
@bhashkar007 hey, is it possible to get this fixed in the Craft plugin store for craft 3 please? It's giving me big issues here. appreciate any help, thanks
